project:
  type: website

website:
  
  navbar:
    title: "Vast Challenge 2023"
    background: "#8cbfeb"
    pinned: true
    right:
      - icon: house-fill
        href: index.qmd
        text: Home
      - proposal.qmd      
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto
  warning: false

editor: visual

