project:
  type: website

website:
  
  navbar:
    title: "Oceanus Watch"
    background: "#8cbfeb"
    pinned: true
    left:
      - text: Home
        href: index.qmd
      - proposal.qmd
      - text: Poster
        href: pdf/VAA_project_poster.pdf
      - text: RShiny App
        href: https://oceanuswatch.shinyapps.io/shinyapp/
    right:
      - icon: person-circle
        href: about.qmd 
      - icon: github
        href: https://github.com/fongbx/vast-challenge-2023
        text: Github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto
  warning: false

editor: visual

